### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by misterquestions** [Holo5/nitro-docker#4]
Hey, just wanted to note that there's missing assets for the project to be run properly.

![image](https://user-images.githubusercontent.com/19508549/193484230-57f0c83e-ca17-487b-83fa-bcd51f3b22ac.png)
![image](https://user-images.githubusercontent.com/19508549/193484238-f2c000e1-1272-4dba-b1bd-b13051300443.png)
![image](https://user-images.githubusercontent.com/19508549/193484248-8b525288-abe1-4b55-a547-f7a7c2e2519d.png)

**Comment by Pi-Bouf** [comment]
Nah, you need to extract assets ! Look at the instructions :)

**Comment by dev-luizf** [comment]
I followed the instructions and had the same problem, after I run "just extract-nitro-assets" some assets aren't copyed to app/nitro-assets/bundled. I think it is some permission problem, because when I run chmod in some of theses folders, it solves part of the problem, but there are some errors in the catalog where for example when i click in "credit furni" it searchs for "icons/CF_1_coin_bronze_icon.png" and not a .nitro file

**Comment by Pi-Bouf** [comment]
But do you have the furnis ? Or only stuff about avatars ?

**Comment by dev-luizf** [comment]
I submitted a pull request to fix the errors. It was caused by the path to the production folder that changed in nitro swf and hot furni url that was missing

**Comment by Pi-Bouf** [comment]
Nice @dev-luizf ! Thanks a lot ;)
